{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-1.0.0.klib",
          "url": "mealz-shared-analytics-js-1.0.0.klib",
          "size": 46254,
          "sha512": "5a3bbce82b496de6d469f49300af7a0de797c342166fc1b0b8f47cc1ef3f15f4c3c23d662ac8629e1992e618bcad4a8ee25815d5af43252ea76b7c09520b6b74",
          "sha256": "b26b2e77c71dc8f748d75af712d925db557fb8b7cdc0b30196090ae12d2a315d",
          "sha1": "f737a4ad2a3873d815319a9022ed75dd435efe32",
          "md5": "a62a5d69fafcbf8c6d8039937d74cb58"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-1.0.0.klib",
          "url": "mealz-shared-analytics-js-1.0.0.klib",
          "size": 46254,
          "sha512": "5a3bbce82b496de6d469f49300af7a0de797c342166fc1b0b8f47cc1ef3f15f4c3c23d662ac8629e1992e618bcad4a8ee25815d5af43252ea76b7c09520b6b74",
          "sha256": "b26b2e77c71dc8f748d75af712d925db557fb8b7cdc0b30196090ae12d2a315d",
          "sha1": "f737a4ad2a3873d815319a9022ed75dd435efe32",
          "md5": "a62a5d69fafcbf8c6d8039937d74cb58"
        }
      ]
    }
  ]
}
