{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-1.0.0.jar",
          "url": "mealz-shared-analytics-1.0.0.jar",
          "size": 12699,
          "sha512": "dbf4bf6f807824d3dca62e0424a08c8ee2467f6b5b8941e4cfcc870a5666bac6246490730e184c174e8513d1db89ad1e6a4e2432d21e01e54335c3d89b135734",
          "sha256": "3de1ce2cbfa8057861b3b1dc877b64d62d1a5b2f74e8545cbde26fd7ec49c300",
          "sha1": "83955d3a5558dae491a43c613ba2e1b8901b0889",
          "md5": "736ff9477a42d83a62e1aaec701d0631"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android-debug/1.0.0/mealz-shared-analytics-android-debug-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android-debug",
        "version": "1.0.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android-debug/1.0.0/mealz-shared-analytics-android-debug-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android-debug",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android/1.0.0/mealz-shared-analytics-android-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android/1.0.0/mealz-shared-analytics-android-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosarm64/1.0.0/mealz-shared-analytics-iosarm64-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosarm64/1.0.0/mealz-shared-analytics-iosarm64-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iossimulatorarm64/1.0.0/mealz-shared-analytics-iossimulatorarm64-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iossimulatorarm64/1.0.0/mealz-shared-analytics-iossimulatorarm64-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosx64/1.0.0/mealz-shared-analytics-iosx64-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosx64/1.0.0/mealz-shared-analytics-iosx64-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-js/1.0.0/mealz-shared-analytics-js-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-js/1.0.0/mealz-shared-analytics-js-1.0.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-js",
        "version": "1.0.0"
      }
    }
  ]
}
