{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-1.0.0.klib",
          "size": 53429,
          "sha512": "6af0ff4b2ca32567075bcdb94fd79928a2d4f49294798287317b85789bcbf2a9f02024427c8d9f905a236fe6f0d4299cc90eadd707b87fb3d32edf18d89ce4ff",
          "sha256": "02091cc93ebaddcb80943bc3572eba2ec6741f408f26d634c261633f32f51759",
          "sha1": "b1083d88843a774ace884e763558a6322f959ff7",
          "md5": "b9130dfff20812710e608c168c3f7394"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-1.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-1.0.0-metadata.jar",
          "size": 3242,
          "sha512": "bf6cd400d7c945ddf50bfb6b69bdc0b9e3eb486a5af0c42abd55b7314d96662391ffd865aa9a62b3dfb34e2cd4c6c1c2ff6000790fe16584a0ee9592715e9c4c",
          "sha256": "e9d42b9497ea5d9e1db943bae31112a1d13a6f2392f9f44e9dfe79ff57acd9ad",
          "sha1": "3d4a839405eaaea95d0b3f3933919ca758bb79f8",
          "md5": "6485246ebd3cc3c91ac6e8adfc26cb6f"
        }
      ]
    }
  ]
}
